### ISSUE TITLE
Sake should be two syllables

### ISSUE THREAD

**Issue by wraithgar** [lukekarrys/emoji-named-characters#6]
I didn't just PR this cause it's worth discussing first, maybe searching through existing emojies.  There is an emoji for sake, the drink, which is two syllables and in that context needs to be two syllables.  I don't think sake, as in "for Pete's sake" is in any emojis, and if it isn't sake should be overridden to be two syllables.

**Comment by lukekarrys** [comment]
I based this off the set at http://www.emoji-cheat-sheet.com/ and searching for sake there only returns :sake:. So I think it should be 2 syllables.

**Comment by wraithgar** [comment]
PR incoming eventually cheers!
